### ISSUE TITLE
Failed to connect to EggBot. :(

### ISSUE THREAD

**Issue by duezero** [cocktailyogi/EggDuino#20]
Hi,

this is my setup now:

ATmega328 on a breadboard, 16MHz
USB serial coverter with reset pin not conneted to ATmega
Eggduino in my ATmega
Inkscape extension 2.7.1

The problem:
Every time I try to plot or check version with Inkscape extension, the error is _"**Failed to connect to EggBot. :(**"_

What I tried to do:
- Send commands via Arduino IDE terminal: everything seems ok. 
- Using an original Arduino UNO instead of ATmega standalone: via Arduino IDE terminal everything is ok but with Inkscape I obtain:  

_Traceback (most recent call last):
  File "eggbot.py", line 1154, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "eggbot.py", line 189, in effect
    self.serialPort = ebb_serial.openPort()
  File "/home/stefano/.config/inkscape/extensions/ebb_serial.py", line 85, in openPort
    foundPort = findPort()
  File "/home/stefano/.config/inkscape/extensions/ebb_serial.py", line 49, in findPort
    if port[1].startswith("EiBotBoard"): #EiBotBoard
AttributeError: 'NoneType' object has no attribute 'startswith'_
 
- Modify **ebb_serial.py** in this way:
_if port[1].startswith("**EiBotBoard**"):_ replacing EiBotBoard with Arduino or USB-Serial converter name.
_if port[2].startswith("**USB VID:PID=04D8:FD92**"):_ replacing VID-PID with Arduino or USB-Serial converter VID-PID

nothing happened, the errors are the same explained above.

I noticed that the serial tx rx LEDs on Arduino or USB-serial converter don't blink when I try to send commands so I think that the problem is a bad assignation of serial port 

I cant find a 2.1 Inkscape extension so I cant try with the patch suggested by cocktailyogi.

Now I don't know what to do so I'm asking here is someone have some suggestions.

Thanks in advance

**Comment by eduoda** [comment]
I realize that it's an old issue, but it may help some one.

In the ebb_serial.py file change the line:
`if port[1].startswith("EiBotBoard"):`
by this one:
`if port[0].startswith("/dev/ttyACM"):`

This sed command will do the job for you:
```
$ cd ~/.config/inkscape/extensions
$ sed -i -e 's/port\[1\].startswith("EiBotBoard")/port\[0\].startswith("\/dev\/ttyACM")/g' ebb_serial.py
```
