### ISSUE TITLE
Connection to EggBot extensions

### ISSUE THREAD

**Issue by bernabap** [cocktailyogi/EggDuino#3]
I don't think there is a bug with the extensions, isn't just trying to find an EiBotBoard?

As we are using something else I tried to change the VID/PID number at line 6 of eggbot_scanwin32.py file to FTDI vendor ID and product ID as I am using arduino nano and it does the job:

hKey = _winreg.OpenKey( hReg, r"SYSTEM\CurrentControlSet\Enum\USB\VID_0403&PID_6001")

For Linux I just had to change from "ttyACM" to "ttyUSB" at line 28 of eggbot_scanlinux.py file.

BTW, great firmware thanks for sharing.

**Comment by cocktailyogi** [comment]
Hi bernabyp,

you patch works as well, but problem is that different Arduinos have different IDs.

I still think, there is a bug in eggbot-extension, because in eggbot.py calls function "getSerialPort"
which first calls eggbot_scan.findEiBotBoards(). If that does not find anything (which is right, because we do not have an Eggbotboard with proper USB-ID), it is supposed to execute function eggbot_scan.findPorts(). Which looks for any devices on serialports.

Problem is, that if findEiBotBoards() does not find anything, findPorts() is not esecuted. I do not really understand why, but that is the problem. If we comment out that block with findEiBotBoards(), everything works like expected.

Yogi

**Comment by jtronics** [comment]
Hello,
i tried to run your arduino-software with inkscape today, but it didn't work.
- EggBotControl Release 2.5.0 date 2015-01-30
- your actual firmware
- I tried your patch and also the patch with the VID/PID of my arduino.
- arduino nano

The arduino is working, because I get the answer "EBBv13_and_above Protocol emulated by Eggduino-Firmware V1.4<\r><\n>"
The Inscape Script is connecting my board (led flashing), but get a wrong answer, so it stops.
"Unable to find an Eggbot on any serial port. :(
Error reading serial data."

**Comment by SpeedGP** [comment]
I have the same issue with jtronics. I've been searching for hours with no success. Unfortunately I have little to no programming experience, but still trying to work through.

Thank you for your work on Eggduino, I really appreciate it.

James

**Comment by cocktailyogi** [comment]
Pid patching  is not recommended method. Disable autoreset on arduinoboard. Evey board has its own instructions.

**Comment by SpeedGP** [comment]
Yeah, I was just about to post this. I just got everything working by using a capacitor on my Uno instead of the recommended resistor. Thanks for your prompt response. And thank you so much for all your effort on this project :)

**Comment by bosko90** [comment]
Hello everybody. I want to make eggbot but I almost suffered a mental breakdown. I'm trying for three days and does not work. 
- The first problem is when I try to install EggDuino returns an error. on the Internet I found the solution that you have to replace that void inline inline void. Then it was loaded onto an Arduino. If i type anything in serial console it won't answer anything.
- In inkscape I get message: Unable to find an Eggbot on any serial port. :(  
I searched the entire Internet and tried everything possible but no luck. 
I was try: 
Open eggbot_scanwin32.py and near the end of file comment out three lines:

if __name__ == '__main__':
#        print "Looking for EiBotBoards"
#        for port in findEiBotBoards():
#               print "  ", port

        print "Looking for COM ports"
        for port in findPorts():
                print "  ", port

and 

First, comment out following lines in file eggbot.py (1386-1390 in my version):

        # Try any devices which seem to have EBB boards attached
#       for strComPort in eggbot_scan.findEiBotBoards():
#           serialPort = self.testSerialPort( strComPort )
#           if serialPort:
#               self.svgSerialPort = strComPort
#               return serialPort

I hope this time it will work. If it does not, let's try to bypass autodetection. Check your COM port name in Device Manager or Arduino IDE (my board appears as COM51) and change one line in eggbot.py (1381) like so:

        # Before searching, first check to see if the last known
        # serial port is still good.

#       serialPort = self.testSerialPort( self.svgSerialPort )
        serialPort = self.testSerialPort( "COM51" )
        if serialPort:
            return serialPort

but without any luck. I gave up over all. 
I have Arduino nano clone with CH340

**Comment by duezero** [comment]
@bosko90  this worked for me [EggDuino-master.zip](https://github.com/cocktailyogi/EggDuino/files/767445/EggDuino-master.zip)

**Comment by bosko90** [comment]
I try these but:  error: 'sendAck' was not declared in this scope

**Comment by bosko90** [comment]
Which version of arduino IDE do you use? and version of inkscape and eggbot extension?

**Comment by SpeedGP** [comment]
I have had a ton of problems with Arduino IDE, you have to use the exact
right version, or else it doesn't work



-James--

**Comment by duezero** [comment]
IDE 1.8.0 -- eggbot 2.7.1 on linux (kubuntu)

**Comment by bosko90** [comment]
I have IDE 1.8.1, eggbot 2.7.1 on windws and eggduino from your link. no luck :( 
I try with nano and uno.

**Comment by duezero** [comment]
ok try this
[EggDuino.zip](https://github.com/cocktailyogi/EggDuino/files/767494/EggDuino.zip)

**Comment by duezero** [comment]
I'm using a UNO stadalone

**Comment by bosko90** [comment]
ok now it was without error.  But if i type anything in serial console it won't answer anything, for check serial comunication.

**Comment by duezero** [comment]
Have you tried different settings in serial monitor? I don't remember now which ones are correct.

Usually I use 1k or 10k resistor on reset pin in my standalone board but I dont think it's the problem

**Comment by bosko90** [comment]
now I was trying all possible baud rate and add 10k ohm resistor.. and nothing

**Comment by bosko90** [comment]
If I try arduino sample: Serial Call and Response it work normaly.

**Comment by duezero** [comment]
try setting " NL&CR 9600baud" and then type TP. The responde should be "OK"

**Comment by bosko90** [comment]
OK that works! thanx.. one step closer.. 
Inkscape still say: Failed to connect to EggBot. :(
Hod can I fix code in "eggbot.py"? instructions that I found are for version 2.4.0.  in 2.7.1. there is no such code. 
![problem2](https://cloud.githubusercontent.com/assets/25691344/22840451/e4b999cc-efcd-11e6-99a7-9e0f15d929c6.jpg)

**Comment by duezero** [comment]
The problem could be the reset pin. If I use an Arduino UNO board, Inkscape fails. Using an Arduino standalone (ATMEGA328 on a breadboard) with reset pin disconnected from the reset signal  Inkscape works.

**Comment by bosko90** [comment]
Are you make any changes on Inkscape extension? 
Now I try 100 ohm and 10k ohm..  no difference..

**Comment by SpeedGP** [comment]
Have you been able to upload the firmware to the Arduino?

**Comment by bosko90** [comment]
Yes. In serial comunication I have response

**Comment by duezero** [comment]
No changes on Inkscape. Reset pin must stay always connected to 5V using a resistor, 10k is good (pull up). But shall be disconnected  from the reset signal (which drives rst pin to ground triggering the reset) once you uploaded the program. You shouId try with a standalone MCU (or maybe cut physically the signal on your NANO but I'm not shure because I dont have a NANO)

**Comment by bosko90** [comment]
here is my knowledge of electronics ends.  It shows that this year we don't have Easter :/

**Comment by SpeedGP** [comment]
I feel like I had this same problem....

I'll look through pictures and see if I can find anything useful



-James--

**Comment by bosko90** [comment]
Now I have response: unknown CMD..

**Comment by SpeedGP** [comment]
I HAD THIS EXACT ISSUE!!!!!

I think this is how I fixed it!!! (Image attached)

You may be able to see my arduino behind it with the breadboard and stuff
plugged in also...may help
https://youtu.be/l_Jm1lLs5U4




-James--

**Comment by bosko90** [comment]
I do not see the image.

**Comment by SpeedGP** [comment]
https://drive.google.com/file/d/0B6X9s6ncrqeqaWstaG5KZmJYV1U/view?usp=sharing



-James--

**Comment by SpeedGP** [comment]
This guy uses a nano and said he had some issues also. You should try this
tutorial, or just use an Uno :P
http://tomscircuits.blogspot.com/2016/05/a-low-cost-eggplotter.html



-James--

**Comment by bosko90** [comment]
thanks for the link. I already tried that but with no luck. I searched the entire Internet and tried every possible solutions. It shows that I am incapable.

**Comment by bosko90** [comment]
I will try with this second link

**Comment by SpeedGP** [comment]
Trust me, I had a ton of issue with the eggduino too....

Upload a different sketch to the nano and see if it's the board.

Did you try the Unicorn plugin or whatever?

Did you use any capacitors?

Have you tried a different USB cable?

Have you tried a different version of Arduino IDE?



-James--

**Comment by duezero** [comment]
You should try Arduino standalone, it's not difficult as it seems ;) https://www.arduino.cc/en/Main/Standalone

**Comment by bosko90** [comment]
I tried Unicorn plugin, but have a lot of errors in generating g code. I do not know with which program would then communicate with arduino. GRBL doesnt work. Now I do not have capacitors. 

duezero: 
I don't have that much electronic. I am mechanical engineer.

**Comment by duezero** [comment]
>  I am mechanical engineer

Me too ;) trust me, try with standalone or try to cut reset signal on your NANO

**Comment by bosko90** [comment]
I do not know where to get all the components. Especially in time.

**Comment by Yura80** [comment]
Take a look at my branch ( https://github.com/Yura80/EggDuino ) for instructions how to patch version 2.7.1 and

**Comment by SpeedGP** [comment]
Here are all of the files I used in 2015
https://drive.google.com/open?id=0B6X9s6ncrqeqdHA2QmZnamFkeGc

I am not sure what worked, or why, but I'd assume your answer is in there
somewhere...

I believe I used Arduino IDE 1.0.6
My Inkscape is version 2.4.1? something like that

You may try spherebot

Good luck. I'm out of ideas



-James--

**Comment by bosko90** [comment]
Yura80 where can I get VID/PID of my arduino? 
SpeedGP I will try..

**Comment by Yura80** [comment]
Device Manager->Ports (COM & LPT)->[your arduino com port]->Properties->Details->Hardware IDs

**Comment by bosko90** [comment]
I didn't find that.. but I tray: 

alternatively, you can replace "EBBport = None" with your specific port number:
    EBBport = "COMxx"               #Windows
    EBBport = "/dev/tty[something]" #Linux/Mac  

change to "COM4" and it's wooooooork!   for now. servo is moving.. Now I must connect the stepping motors. Hope it is work.. Yura80 thanx! and of course thanks to all of you I offer assistance. Now it is 8 hours behind me. If I need anything I write tomorrow.

**Comment by SpeedGP** [comment]
I guess we all assumed you had the correct COM port.... 51 did sound a
little high, but who am I to judge. Glad you got it working!



-James--

**Comment by bosko90** [comment]
No I always knew that is COM4. But in the extension for Inkscape I didnt know how to fix. your link has helped.
Now I have to set the proper size of steps. The motor is rotated four times instead of once.

**Comment by Asenom** [comment]
Hello to you all,

I'm new to GitHub and joined to talk with you about my issue. I tried everything you posted before and i also tried @duezero versions of Eggduino. With the newest IDE 1.8. I can't get his sketch to run through my compiler. It get stuck everytime by this Part and I dont know how to fix it. 
"
Helper_Functions:4: error: 'SELFPRGEN' was not declared in this scope
SPMCSR &= ~SELFPRGEN;

exit status 1

'SELFPRGEN' was not declared in this scope"

Do you have any clue what I should change to your Sketch to get it running?

Funfact aside: I tried "Ejjduino" the Eggbot Version from jjrobot and it worked fine on my ArduinoMEGA. I could also connect it to Eggbot Inkscape extension, after some modifications. But it failed to move.

**Comment by SpeedGP** [comment]
Duezero posted this last time:
Try this one

https://github.com/cocktailyogi/EggDuino/files/767494/EggDuino.zip

Or

https://github.com/cocktailyogi/EggDuino/files/767445/EggDuino-master.zip

Other than that, try older versions of IDE

On Feb 22, 2017 4:47 PM, "Asenom" <notifications@github.com> wrote:

Hello to you all,

I'm new to GitHub and joined to talk with you about my issue. I tried
everything you posted before and i also tried @duezero
<https://github.com/duezero> versions of Eggduino. With the newest IDE 1.8.
I can't get his sketch to run through my compiler. It get stuck everytime
by this Part and I dont know how to fix it.
"
Helper_Functions:4: error: 'SELFPRGEN' was not declared in this scope
SPMCSR &= ~SELFPRGEN;

exit status 1

'SELFPRGEN' was not declared in this scope"

Do you have any clue what I should change to your Sketch to get it running?

Funfact aside: I tried "Ejjduino" the Eggbot Version from jjrobot and it
worked fine on my ArduinoMEGA. I could also connect it to Eggbot Inkscape
extension, after some modifications. But it failed to move.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cocktailyogi/EggDuino/issues/3#issuecomment-281853928>,
or mute the thread

**Comment by duezero** [comment]
Probably MEGA2560 is not supported yet. I have the same issue if I try to compile for a MEGA2560. You need to use an Arduino UNO or NANO (ATmega328).   IDE1.8.1 works fine. 

Maybe I'll check later if it's possible fix this issue but you don't really need a Mega2560 for this project

**Comment by Asenom** [comment]
Thank you for your reply, yeah i know it's some kind of overpowered, but it was already laying around so i gave it a try!  Yeah, i will try out some other trouble shooting in the evening! Thank you! i would apreciate it!

**Comment by duezero** [comment]
I tried to replace
_SPMCSR &= ~SELFPRGEN;_
with
_SPMCSR &= ~SPMEN;_

and now it compiles both for UNO and MEGA. 

I don't have a Mega so cannot test it (:

**Comment by Asenom** [comment]
Thank you very much! I tried it and it seems to work with all the other changes! I also tried to connect with the Inkscape extensions and by checking for the EBB Version it also replied with the right Version. I think the communication is now properly working!  I will give a reply on how it worked with steppers and the servo motors, but first i have to change the PINs!

Thank you very much! :)

**Comment by SpeedGP** [comment]
Different topic,
is there any way I could run the Gcode while it's in the Arduino code? My
plan is to push a button, draw an egg, push a button, draw an egg, etc.
(Science fair project)

Thanks!

**Comment by duezero** [comment]
> Different topic, is there any way I could run the Gcode while it's in the Arduino code? My plan is to push a button, draw an egg, push a button, draw an egg, etc.

I think you should re-design the whole firmware. Actually the program reads commands sent by Inkscape extension that are NOT g-code. Conversion from "drawing-->G-code-->eggbot commands" is performed by inkscape extension

**Comment by SpeedGP** [comment]
Interesting, thanks!

Unfortunately I'm no programmer, I can tweak, but not really write... Just
checking if it was easy.

Thanks!



-James--

**Comment by rahendri** [comment]
Hi, my eggbot keeps turning into the same direction, it does not matter if i send an SM,1000,0,-800 or SM,1000,0,800 (even quick after eachother.) I use and arduino Leonardo together with an Adafruit motorshield V.2.3. I already changed some of to code to have this working.  Any idea on how to fix this?

**Comment by ellow7** [comment]
I got the error message "Failed to connect to EggBot. :(" every time in Inkscape, however I could use the serial interface from the arduino IDE without problems (e.g. sending "v" and receiving the version).
After some research I found that my extension/serial in inkscape was outdated. After updating everything worked -> https://github.com/pyserial/pyserial/tree/master/serial
